### ISSUE TITLE
How to run the UI?

### ISSUE THREAD

**Issue by aahutsal** [softsky/Spitfire#1]
@nazarlitvin plz, create README.org (use emacs `org-mode`) and document `Install` an `How to run` sections.

Currently I'm getting this trying review with `npm start`:

![screenshot_2018-07-05-07:56:46.png](https://images.zenhubusercontent.com/5858bccbb9dc3c622023c83b/7638b22c-b08b-4f31-8b10-8ffcd69ea067)

**Comment by aahutsal** [comment]
@nazarlitvin any update on this?

**Comment by nazarlitvin** [comment]
@gutsal-arsen I did create a README.md with instructions how to run Spitfire application.
