### ISSUE TITLE
Login flow

### ISSUE THREAD

**Issue by nazarlitvin** [softsky/Spitfire#5]
### Reproduce and describe mobile application login flow. 

I've already checked a mobile traffic and successfully did a login request with curl.

Seems like we should make an `appIninialization` request to get `Set-Cookie`  header and then perform a `login` request itself. 

All CURL requests are committed to the BE repo.

**Comment by aahutsal** [comment]
Moved to appropriate repo: https://github.com/softsky/spitfire-backend/issues/2
